[project]
name = "PySide Widgets Project"

[tool.pyside6-project]
files = ["crud.py", "kurir.py", "kurir.ui", "main.py", "main.ui", "produk.py", "produk.ui", "toko.py", "toko.ui", "transaksi.py", "transaksi.ui"]
